#pragma once

/*
	Using in autogenerated boilerplate codes.
*/
#define HFUNC_RESULT_PARAM __Function_Param_Result
#define HFUNC_RESULT_DECL void* const HFUNC_RESULT_PARAM

#define HFUNC_THIS_PTR (Instance)
#define HFUNC_THIS_CAST(ClassType) ((ClassType*)Instance)
#define FUNC_THIS HFUNC_THIS_CAST(ThisClass)




