#pragma once
#define HOPSTEP_USING_STD_ANY 1
/*
	Using in autogenerated boilerplate codes.
*/
#define HFUNC_RESULT_PARAM __Function_Param_Result
#if HOPSTEP_USING_STD_ANY
#define HFUNC_RESULT_DECL std::any HFUNC_RESULT_PARAM
#define HFUNC_RESULT_DECL_INNER std::any* HFUNC_RESULT_PARAM
#define HFUNC_RESULT_TYPECAST(Result) (Result) 
#else
#define HFUNC_RESULT_DECL void* HFUNC_RESULT_PARAM
#define HFUNC_RESULT_DECL_INNER void** HFUNC_RESULT_PARAM
#define HFUNC_RESULT_TYPECAST(Result) (void*)(Result)
#endif

#define HFUNC_THIS_PTR (Instance)
#define HFUNC_THIS_CAST(ClassType) ((ClassType*)Instance)
#define HFUNC_THIS HFUNC_THIS_CAST(ThisClass)

/*
	
*/
#define HFUNC_GET_FROM_FRAME(ParamType, ParamName) ParamType ParamName = (Frame.PopByType<ParamType>());
